# Generated by Django 3.0.1 on 2021-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_uk', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=2500)),
                ('text_en', models.CharField(max_length=2500, null=True)),
                ('text_ru', models.CharField(max_length=2500, null=True)),
                ('text_uk', models.CharField(max_length=2500, null=True)),
            ],
        ),
    ]
